# Generated by Django 6.0 on 2025-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_number',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current progress number', max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_number',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target number (e.g., 100)', max_digits=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='unit',
            field=models.CharField(choices=[('km', 'Kilometers'), ('miles', 'Miles'), ('kg', 'Kilograms'), ('lbs', 'Pounds'), ('workouts', 'Workouts'), ('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('reps', 'Repetitions'), ('sets', 'Sets')], default='workouts', help_text='Unit of measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_value',
            field=models.CharField(blank=True, help_text="e.g., '100km', '20 workouts', '5kg'", max_length=100),
        ),
    ]
