# Generated by Django 6.0 on 2025-12-30 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal_current_number_goal_target_number_goal_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_workout', '🎯 First Step'), ('10_workouts', '💪 Getting Strong'), ('7_day_streak', '�� On Fire'), ('first_goal', '⭐ Goal Crusher'), ('custom_exercise', '✨ Innovator'), ('50_workouts', '🚀 Dedicated'), ('30_day_streak', '👑 Champion')], max_length=20)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_date'],
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
