from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime


def generate_workouts_pdf(workouts, user):
    """Generate PDF report of user's workouts"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#a855f7'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#ec4899'),
        spaceAfter=12,
    )
    
    # Title
    title = Paragraph(f"💪 FitTrack Aura - Workout Report", title_style)
    elements.append(title)
    
    # User info
    user_info = Paragraph(f"<b>User:</b> {user.username} | <b>Generated:</b> {datetime.now().strftime('%B %d, %Y')}", styles['Normal'])
    elements.append(user_info)
    elements.append(Spacer(1, 20))
    
    # Summary
    summary = Paragraph(f"<b>Total Workouts:</b> {workouts.count()}", heading_style)
    elements.append(summary)
    elements.append(Spacer(1, 12))
    
    # Workouts table
    if workouts.exists():
        data = [['Date', 'Title', 'Duration', 'Exercises']]
        
        for workout in workouts:
            exercise_count = workout.workout_exercises.count()
            data.append([
                workout.date.strftime('%m/%d/%Y'),
                workout.title[:30],
                f"{workout.duration or 0} min",
                str(exercise_count)
            ])
        
        table = Table(data, colWidths=[1.5*inch, 3*inch, 1.5*inch, 1.5*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#a855f7')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        elements.append(table)
    else:
        no_data = Paragraph("No workouts found.", styles['Normal'])
        elements.append(no_data)
    
    # Footer
    elements.append(Spacer(1, 30))
    footer = Paragraph("Generated by FitTrack Aura | © 2025", styles['Normal'])
    elements.append(footer)
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_goals_pdf(goals, user):
    """Generate PDF report of user's goals"""
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#a855f7'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#ec4899'),
        spaceAfter=12,
    )
    
    # Title
    title = Paragraph(f"🎯 FitTrack Aura - Goals Report", title_style)
    elements.append(title)
    
    # User info
    user_info = Paragraph(f"<b>User:</b> {user.username} | <b>Generated:</b> {datetime.now().strftime('%B %d, %Y')}", styles['Normal'])
    elements.append(user_info)
    elements.append(Spacer(1, 20))
    
    # Summary
    completed = goals.filter(is_completed=True).count()
    active = goals.filter(is_completed=False).count()
    summary = Paragraph(f"<b>Total Goals:</b> {goals.count()} | <b>Completed:</b> {completed} | <b>Active:</b> {active}", heading_style)
    elements.append(summary)
    elements.append(Spacer(1, 12))
    
    # Goals table
    if goals.exists():
        data = [['Title', 'Target', 'Progress', 'Status', 'Due Date']]
        
        for goal in goals:
            status = "✅ Complete" if goal.is_completed else "🔄 Active"
            data.append([
                goal.title[:25],
                f"{goal.target_display} {goal.get_unit_display()}",
                f"{goal.progress_percentage}%",
                status,
                goal.target_date.strftime('%m/%d/%Y')
            ])
        
        table = Table(data, colWidths=[2*inch, 1.5*inch, 1*inch, 1.2*inch, 1.3*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#a855f7')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
        ]))
        
        elements.append(table)
    else:
        no_data = Paragraph("No goals found.", styles['Normal'])
        elements.append(no_data)
    
    # Footer
    elements.append(Spacer(1, 30))
    footer = Paragraph("Generated by FitTrack Aura | © 2025", styles['Normal'])
    elements.append(footer)
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer
